version: '3' 
services:
    db:
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: db-api-lancamentos
            POSTGRES_USER: db-api-lancamentos
            POSTGRES_DB: api-lancamentos
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - '5432:5432'